Create zh_cn.json
TehNut-Mods/HWYLA pull request #156
Opened 2019-04-24 02:57 UTC by XuyuEre

2019-04-25 17:57 UTC, TehNut commented
@3TUSK mind giving this a once-over?

2019-04-26 00:30 UTC, 3TUSK requested changes
I was summoned. Quickly assembled a fabric modpack for proofreading and here we go:

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "tooltip.waila.mode_comparator": "比较仪",
比较器

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "tooltip.waila.delay": "延迟: %d",
全角冒号。
`延迟：%d`
上同。
下同。

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "tooltip.waila.health": "%s/%s 生命值",
`生命值：%d/%d`？

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "key.waila.toggle_liquid": "切换液体",
显示液体？

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.sneaky_details_desc": "正文是隐藏的,除非按住潜行键",
仅当潜行时显示正文。

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.display_mode_desc": "工具提示显示的行为\n切换: 显示快捷键将会切换开与关\n保持: 显示键必须按下",
全角冒号

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.plugin_waila.show_registry": "显示注册的名字",
显示注册名

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.format_mod_name": "Mod名称",
Mod 名

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.format_block_name": "方块名称",
方块名

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.format_fluid_name": "流体名称",
流体名

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.format_entity_name": "实体名称",
实体名

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.format_registry_name": "注册名称",
注册名

2019-04-26 00:30 UTC, 3TUSK commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.overlay_pos_x": "横比",
……“横向相对位置”？“X 轴位置”？总之只说“比（值）”肯定时模糊不清的。

需要讨论，下同。@TartaricAcid

2019-04-26 01:01 UTC, XuyuEre commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "key.waila.toggle_liquid": "切换液体",
虽然原文本是toggle，但是的确显示液体更符合，谢谢

2019-04-26 01:01 UTC, XuyuEre commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.overlay_pos_x": "横比",
x轴位置 默认为0.5, 0.0为屏幕最左。1.0为屏幕最右。这样来看应该是相对位置吧

2019-04-26 01:01 UTC, XuyuEre commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.overlay_pos_x": "横比",
y轴  1.0最上，0.0最下

2019-04-26 01:03 UTC, XuyuEre commented
Fixed translation error，thanks @3TUSK

2019-04-26 06:22 UTC, liach commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "entity.minecraft.villager.none": "傻子"
“失业”更好吧，nitwit才是傻子

2019-04-26 12:13 UTC, XuyuEre commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "entity.minecraft.villager.none": "傻子"
这好像是1.14新内容是吧，谢谢

2019-04-26 12:27 UTC, XuyuEre commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "entity.minecraft.villager.none": "傻子"
失业者

2019-04-26 17:26 UTC, liach commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "entity.minecraft.villager.none": "傻子"
@TehNut turns out the english localization for unemployed villager is wrong (it's incorrectly reported as nitwit)

2020-06-03 16:02 UTC, Artoria2e5 commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "tooltip.waila.delay": "延迟: %d",
未解决，为什么就 resolve 了？

2020-06-03 16:02 UTC, Artoria2e5 commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "config.waila.formatting": "格式化",
叫格式就够了
```suggestion
  "config.waila.formatting": "格式",
```

2020-06-03 16:02 UTC, Artoria2e5 commented on src/main/resources/assets/waila/lang/zh_cn.json
> +  "entity.minecraft.villager.none": "失业者"
#202 解决后可以用上：
```suggestion
  "entity.minecraft.villager.none": "失业者",
  "entity.minecraft.villager.nitwit": "傻子"
```

2020-08-15 23:39 UTC, closed without merging