Updated de_DE.lang to match latest version
TehNut-Mods/HWYLA pull request #37
Opened 2017-01-14 00:19 UTC by X00LA

Added missing strings and corrected some spellings.

2017-01-14 00:29 UTC, TehNut requested changes
In general, if you could remove all the strings that don't exist in `en_US.lang`, it would be appreciated.

2017-01-14 00:29 UTC, TehNut commented on src/main/resources/assets/waila/lang/de_DE.lang
> +cfg.theme.vanilla=Vanilla
Since this is the same as in `en_US.lang`, it doesn't need to be here

2017-01-14 00:29 UTC, TehNut commented on src/main/resources/assets/waila/lang/de_DE.lang
> +screen.button.modules=Module
Same for these two.

2017-01-14 00:29 UTC, TehNut commented on src/main/resources/assets/waila/lang/de_DE.lang
> +enchant.title.maxlvl=Max Lvl
These three don't even exist in the current `en_US.lang`.

2017-01-14 00:42 UTC, X00LA commented
Fixed the issues.

Regards

2017-01-23 03:03 UTC, TehNut approved these changes

2017-01-23 03:04 UTC, TehNut commented
Could you fix the conflicts so I can merge this?

2017-01-23 12:50 UTC, closed without merging

2017-01-23 12:50 UTC, X00LA commented
New Request for 1.11